### ISSUE TITLE
Pinned github action hash in workflows

### ISSUE THREAD

**Issue by tchapacan** [tchapacan/livebox-exporter-rs#21]
Purpose of this issue is to keep track of a security improvment in the workflows of the repo regarding of the pinned hash of used github actions

- ex: 

```
- name: "Checkout repo 👉"
        uses: actions/checkout@v4
```

vs

```
- name: "Checkout code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
```
